import { useId, useMemo } from 'react'
import type { ReactNode } from 'react'
import styled from 'styled-components'
import { Label } from '../Label'
import { StatusMessage } from '../Input'
import { FieldContext } from './context'
import type { FieldContextValue, FieldStatus } from './context'

export interface FormFieldProps {
  /** Field label; rendered in a <label> associated with the control. */
  label: ReactNode
  /** Optional helper text under the control. */
  description?: ReactNode
  /** Error message (red); when truthy the field is in its error status. */
  error?: ReactNode
  /** Warning message (yellow); shown when there is no error. */
  warning?: ReactNode
  /** Success message (green); shown when there is no error or warning. */
  success?: ReactNode
  required?: boolean
  /** Override the auto-generated control id (rare — the id is generated by default). */
  htmlFor?: string
  className?: string
  /** The control — an Input, Textarea, Select, … that self-wires via useFieldControl. */
  children: ReactNode
}

const Root = styled.div`
  display: flex;
  flex-direction: column;
  gap: 0.375rem;
`

const FieldLabel = styled(Label)`
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
`

const RequiredMark = styled.span`
  color: ${({ theme }) => theme.colors.brand};
`

const Description = styled.p`
  font-size: ${({ theme }) => theme.fontSize.xs};
  color: ${({ theme }) => theme.colors.muted};
  margin: 0;
`

/** Semantic status precedence: a hard error outranks a warning, which outranks success. */
function resolveStatus(
  error?: ReactNode,
  warning?: ReactNode,
  success?: ReactNode,
): { status: FieldStatus; message: ReactNode } | null {
  if (error) return { status: 'error', message: error }
  if (warning) return { status: 'warning', message: warning }
  if (success) return { status: 'success', message: success }
  return null
}

/**
 * Thin, composable, RHF-agnostic field wrapper (ADR-0075). Owns the
 * label/description/status scaffolding and the accessibility wiring (id,
 * htmlFor, aria-describedby, aria-invalid, aria-required); the control is
 * dropped in as children and wires itself through `useFieldControl`.
 *
 * Renders one semantic status at a time (ADR-0157) — `error` (red) outranks
 * `warning` (yellow) outranks `success` (green) — colouring both the message
 * and the control's border via context.
 */
export function FormField({
  label,
  description,
  error,
  warning,
  success,
  required = false,
  htmlFor,
  className,
  children,
}: FormFieldProps) {
  const reactId = useId()
  const controlId = htmlFor ?? `field-${reactId}`
  const descriptionId = description ? `${controlId}-description` : undefined

  const resolved = resolveStatus(error, warning, success)
  const status = resolved?.status
  const statusId = status ? `${controlId}-status` : undefined

  const ctx = useMemo<FieldContextValue>(
    () => ({ controlId, descriptionId, statusId, status, required }),
    [controlId, descriptionId, statusId, status, required],
  )

  return (
    <FieldContext.Provider value={ctx}>
      <Root className={className}>
        <FieldLabel htmlFor={controlId}>
          {label}
          {required && <RequiredMark aria-hidden="true">*</RequiredMark>}
        </FieldLabel>
        {children}
        {description && <Description id={descriptionId}>{description}</Description>}
        {resolved && (
          <StatusMessage
            id={statusId}
            $status={resolved.status}
            role={resolved.status === 'error' ? 'alert' : undefined}
          >
            {resolved.message}
          </StatusMessage>
        )}
      </Root>
    </FieldContext.Provider>
  )
}
